server:
  port: 30010
spring:
  application:
    name: microtest
  jmx:
    default-domain: microtest
  security:
    user:
      name: onaemo
      password: tatteam@798184
      roles: ADMIN
  devtools:
    livereload:
      enabled: false
  rabbitmq:
    micromq:
      virtual-host: /micro_vhost
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      host: tatteam82.cafe24.com
      port: 5672
eureka:
  instance:
    hostname: 127.0.0.1
    port: 30000
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    eureka-server-read-timeout-seconds: 30
    service-url:
      defaultZone: http://onaemo:1111@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS


keycloak:
  enabled: false

keycloak-client:
  server-url: https://steelk.onaemo.com/auth
  realm: Steel
  realm-url: https://steelk.onaemo.com/auth/SteelApplication

custom:
  message: Hello, api-dev! Cloud Bus Test!!
